version: '2'
volumes:
    sense-data:
services:
  influxdb:
    image: influxdb:1.8.10
    hostname: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
    restart: always
    volumes:
      - sense-data:/var/lib/influxdb

  grafana:
    restart: always
    build: ./grafana
    hostname: grafana
    container_name: grafana
    ports:
      - "80:80"
    volumes:
      - 'sense-data:/data'
    environment:
      - 'GF_SERVER_HTTP_PORT=80'
      - 'GF_PATHS_PROVISIONING=/usr/src/app/provisioning'
      - 'GF_SESSION_PROVIDER=memory'
    depends_on:
      - influxdb

  counter:
    hostname: counter
    container_name: counter
    restart: always
    build: ./counter
    privileged: true
    environment:
      - VERBOSE=true
      - DB_OUTPUT=prometheus