version: '2'

volumes:
    sense-data:

services:
  influxdb:
    profiles:
      - local_everything
    image: influxdb:1.8.10
    hostname: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
    restart: unless-stopped
    volumes:
      - sense-data:/var/lib/influxdb

  grafana:
    profiles:
      - donotstart
    restart: always
    build: ./grafana
    hostname: grafana
    container_name: grafana
    ports:
      - "80:80"
    volumes:
      - 'sense-data:/data'
    environment:
      - 'GF_SERVER_HTTP_PORT=80'
      - 'GF_PATHS_PROVISIONING=/usr/src/app/provisioning'
      - 'GF_SESSION_PROVIDER=memory'
    depends_on:
      - influxdb

  counter:
    hostname: counter
    container_name: counter
    restart: unless-stopped
    build: ./counter
    privileged: true
    ports:
      - "9274:9274"
    environment:
      - VERBOSE=true
      - DB_OUTPUT=prometheus
    tmpfs:
      - /run:rw,nosuid,nodev,exec,relatime,size=256M
      - /tmp:rw,nosuid,nodev,noexec,relatime,size=128M
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
