#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091

# Copyright 2023 Ramon F Kolb https://github.com/kx1t
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /scripts/common

if [[ "${DB_OUTPUT,,}" == "prometheus" ]]; then
    while [[ ! -f /run/prometheus.prom ]]
    do
        sleep 1
    done
    trap "pkill -P $$ || true; s6wrap --timestamps --prepend=prometheus-readsb --quiet --args echo 'service stopping'; exit 0" SIGTERM SIGINT SIGHUP SIGQUIT
    echo -e "HTTP/1.1 200 OK\nContent-Type: text/plain\n\n$(cat /run/prometheus.prom)" | ncat -l 9274 > /dev/null 2>&1 &
    wait
else
    exec sleep infinity
fi