#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1091

source /scripts/common
cd /usr/share/geiger-counter || exit 1

if chk_enabled "${VERBOSE}"; then
    export GEIGER_VERBOSE="true"
fi 

s6wrap --prepend=counter --timestamps --args python3 -u counter.py
